version: "3.9"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  golang-app:
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: dev
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - database
    volumes:
      - .:/opt/app/api
volumes:
  data: